# Generated by Django 5.0.7 on 2024-08-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cabin", "0002_alter_admin_id_alter_car_id_alter_driver_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="email",
            field=models.EmailField(max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="car_type",
            field=models.CharField(
                choices=[("A", "Class A"), ("B", "Class B"), ("C", "Class C")],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="dropoff_time",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="ride",
            name="pickup_time",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="riderequest",
            name="car_type",
            field=models.CharField(
                choices=[("A", "Class A"), ("B", "Class B"), ("C", "Class C")],
                max_length=3,
            ),
        ),
    ]
